#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Apr 14 14:21:26 2019

@author: jinyanliu
"""
import numpy
from matplotlib import pylab

principal = 10000  # initial investment
interestRate = 0.05
years = 20
values = []
for i in range(years + 1):
    values.append(principal)
    principal += principal * interestRate
pylab.rcParams['lines.markersize'] = 10
pylab.xticks(numpy.arange(0, 21, 1.0))
pylab.plot(values)
pylab.plot(values, 'ko')
pylab.show()
